name: Gimlog Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Build
      run: xcodebuild clean build -project "Gimlog/Gimlog.xcodeproj" -scheme "Gimlog" -destination "platform=iOS Simulator,name=Any iOS Simulator Device" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Run unit tests Game module
      run: xcodebuild test -project "../Gimlog.xcodeproj" -scheme "Game" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" | xcpretty && exit ${PIPESTATUS[0]}